{% set version = "4.2.0" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 87d677c6450a17a4dd8cfa1c7ae5f1f7646c47b63dab5abd88980093a47611e5

build:
    number: 2
    script: $PYTHON setup.py install  # [unix]
    # ajgpitch 2017-03-16: win py27 build currently failing due to error on import scipy.misc
    # Trying again on a new build
    skip: True                        # [win and py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython >=0.21
    - scipy >=0.15
    - toolchain
    
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.15
    - cython >=0.21
    
test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
    - nonhermitian
