{% set version = "4.4.0" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 67170ad5b58a36ac6b250601643a18ae73b3826c61f630744225765a3c9f07f7
    #v4.1.0 build 2: sha256: b41963d33662121d3f996c5c4f8f28a63c5253d5ffb3f4e1a4e88d84e213b006
    #v4.2.0 build 2: sha256: 87d677c6450a17a4dd8cfa1c7ae5f1f7646c47b63dab5abd88980093a47611e5

build:
    number: 0
    script: python -m pip install --no-deps --ignore-installed . --verbose  # [unix]
    # ajgpitch 2017-03-16: win py27 build currently failing due to error on import scipy.misc
    # ajgpitch 2017-07-28: decided to give up on win py2k build until further notice
    skip: True                        # [win and py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.21
    - scipy >=0.15
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy >=0.15
    - cython >=0.21
    
test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
    - nonhermitian
