{% set version = "5.1.0" %}

package:
  name: qutip
  version: {{ version }}

source:
  url: https://github.com/qutip/qutip/archive/v{{ version }}.tar.gz
  sha256: 771c9019891eacf9377063fdf002484b7de2a90fd1ed1142c9194f4945511fce

build:
  number: 0
  skip: true  # [py<39]
  skip: true  # [py==39 and python_impl == 'pypy' and not linux]
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.20                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython >=0.29.20
    - scipy >=1.0
    - packaging
  run:
    - python
    - setuptools
    - scipy >=1.0
    - packaging

test:
  imports:
    - qutip

about:
  home: http://qutip.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control

extra:
  recipe-maintainers:
    - ajgpitch
    - quantshah
    - nathanshammah
    - ericgig
    - hodgestar
