{% set version = "4.2.0" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 6db67ca5eb720e2cf5fb9651430c0d62a46198e2fe0c42c8d56ef11e2fc48cc6
    # This log of builds should be maintained in case previous versions ever need to be rebuilt.
    # It should show the last build number and corresponding sha256 for the last minor release,
    # which should match that of the tarball of the version on the download url
    #v4.1.0 build 2: sha256: b41963d33662121d3f996c5c4f8f28a63c5253d5ffb3f4e1a4e88d84e213b006
    #v4.2.0 build 3: sha256: 6db67ca5eb720e2cf5fb9651430c0d62a46198e2fe0c42c8d56ef11e2fc48cc6

build:
    number: 3
    script: $PYTHON setup.py install  # [unix]
    # ajgpitch 2017-03-16: win py27 build currently failing due to error on import scipy.misc
    # ajgpitch 2017-07-28: decided to give up on win py2k build until further notice
    skip: True                        # [win and py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython >=0.21
    - scipy >=0.15
    - toolchain
    
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.15
    - cython >=0.21
    
test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
    - nonhermitian
