{% set version = "4.1.0" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 16f32fd3d8c09de2bca3959bb5c72425fa87e5c05b238e558c8e095e65b4e1a4

build:
    number: 0
    script: $PYTHON setup.py install  # [unix]

requirements:
  build:
    - python
    - setuptools
    - cython >=0.21
    - numpy x.x
    - scipy >=0.15
    - mingwpy                         # [win and (py2 or py34)]
    
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.15
    - cython >=0.21
    - mingwpy                         # [win and (py2 or py34)]
    
test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
