{% set version = "4.6.1" %}

package:
    name: qutip
    version: {{ version }}

source:
    url: https://github.com/qutip/qutip/archive/v{{ version }}.tar.gz
    sha256: 01f9564a5f87dbee783add707d546b646932a6edad946bfe09787727f52211e9

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython >=0.29.20
    - scipy >=1.0
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0

test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - quantshah
    - nathanshammah
    - ericgig
    - nathanshammah
    - jakelishman
    - hodgestar
