{% set version = "4.7.4" %}

package:
  name: qutip
  version: {{ version }}

source:
  url: https://github.com/qutip/qutip/archive/v{{ version }}.tar.gz
  sha256: 94fe4c96ec1b43e33a78ec7f4794278a539f86f28a3dfc1ae0922d6760f18d80

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.20,<3.0.0                # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython >=0.29.20,<3.0.0
    - scipy >=1.0
    - packaging
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0
    - packaging

test:
  imports:
    - qutip

about:
  home: http://qutip.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control

extra:
  recipe-maintainers:
    - ajgpitch
    - quantshah
    - nathanshammah
    - ericgig
    - nathanshammah
    - jakelishman
    - hodgestar
